### ISSUE TITLE
Error 500 while trying to access /api/v5/rest/folders

### ISSUE THREAD

**Issue by v0tti** [dbermuehler/pypleasant#2]
Hey,
I would like to us this tool, but I can't get it to work. It tries to request `https://example.com/api/v5/rest/folders` but gets an error 500. The domain seems to be correct as the OAuth works fine.
Connecting to `https://example.com/api/v5/rest/folders` manually also results in error 500, sub-folders work fine.

```
pleasant-cli /Root/Somefolder/Someentry --username --debug                                                                                                                        
DEBUG: Starting new HTTPS connection (1): example.com:443
DEBUG: https://example.com:443 "GET /oauth2/token HTTP/1.1" 200 954
DEBUG: Starting new HTTPS connection (1): example.com:443
DEBUG: https://example.com:443 "GET /api/v5/rest/folders HTTP/1.1" 500 36
ERROR: 500 Server Error: Internal Server Error for url: https://example.com/api/v5/rest/folders
```

**Comment by v0tti** [comment]
Seems like I am running into this issue of the password server: https://pleasantsolutions.com/info/pleasant-password-server/x-common-issues#v5APIError500

**Comment by dbermuehler** [comment]
Hi @v0tti thanks for raising this issue. I added the X-Pleasant-Client-Identifier header. Does this solve the issue for you?

**Comment by v0tti** [comment]
Yes, works fine now. Thanks for the fix!
